version: '2'
services:
    jhe2e-mysql:
        image: mysql:5.7.19
        # volumes:
        #     - ~/volumes/jhipster/JHE2E/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhe2e
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp
